FROM mcr.microsoft.com/playwright:v1.54.1-jammy

WORKDIR /app

COPY package.json yarn.lock ./
RUN corepack enable && corepack prepare yarn@4.5.3 --activate
RUN yarn install

COPY . .
RUN mkdir -p /app/allure-results
RUN npx playwright install --with-deps chromium

ENV ENV=dev
CMD ["yarn", "run-tests-headless"]