name: Run Playwright tests in Docker

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack and install Yarn 4
        run: |
          corepack enable
          corepack prepare yarn@4.5.3 --activate
          yarn install

      - name: Run tests inside Docker
        run: docker-compose -f docker-compose.local.yml up --build --abort-on-container-exit

      - name: Generate Allure report
        run: |
          npx allure generate ./allure-results --clean -o ./allure-report

      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./allure-report